# Generated by Django 3.0.3 on 2020-03-28 14:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('description', models.TextField()),
                ('location', models.TextField(blank=True)),
                ('tag', models.TextField(blank=True)),
                ('chosen_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chosen_offer', to=settings.AUTH_USER_MODEL)),
                ('int_users', models.ManyToManyField(related_name='int_offers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
