# Generated by Django 3.0.3 on 2020-03-19 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='usual_wait',
            new_name='bio',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='orders_count',
        ),
    ]
