# Generated by Django 3.0.3 on 2020-04-01 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='title',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
