# Generated by Django 3.0.3 on 2020-03-28 19:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0002_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='chosen_user',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chosen_offer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='offer',
            name='description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='int_users',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='int_offers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='offer',
            name='location',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='tag',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
