# Generated by Django 3.0.3 on 2020-04-09 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_interest'),
    ]

    operations = [
        migrations.AddField(
            model_name='interest',
            name='int_description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
